### ISSUE TITLE
关于image-captioning-oscar

### ISSUE THREAD

**Issue by qvqqa** [Alive1024/cube-dl#8]
您好，关于您仓库中那篇image-captioning-oscar，请问能否能提供一下最后在coco caption数据集上输出的结果？我想用来做对比。

**Comment by Alive1024** [comment]
你好，由于时间有些久远，当时在数据集上的预测结果已经清理掉了，有需要的话可以按照该仓库中给出的步骤操作、使用 Oscar 官方提供的模型在 COCO Caption 上进行推理来获得结果。
